# Generated by Django 4.0.3 on 2022-03-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.IntegerField(default=0),
        ),
    ]
