# Generated by Django 4.0.3 on 2022-04-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('postID', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
