# Generated by Django 4.0.3 on 2022-03-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('favorite', models.CharField(max_length=120)),
                ('bios', models.CharField(max_length=120)),
                ('pronouns', models.CharField(max_length=120)),
                ('artist', models.CharField(max_length=120)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
